---
title: "Week 3 homework solutions"
author: "Hanusia Higgins"
date: "1/29/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


### 1.
##### Before:  
First String    Second      1.22      3.4  
Second          More Text   1.555555  2.2220  
Third           x           3         124  

##### Find: `\h+`
##### Replace: `,`

```explanation
In this solution, "\h+" selects any (one or more) consecutive tabs or spaces, and "," replaces each of those instances with a comma.
```

##### After:  
First,String,Second,1.22,3.4  
Second,More,Text,1.555555,2.2220  
Third,x,3,124  

### 2.
##### Before:  
Ballif, Bryan, University of Vermont  
Ellison, Aaron, Harvard Forest  
Record, Sydne, Bryn Mawr  


##### Find: `(\w+),\s(\w+),\s(.*)`
##### Replace: `\2 \1 \(\3\)`

```explanation
The first and second captures get each person's last and first name, respectively; ",\s" accounts for the comma and space sequences; the third capture gets the rest of the line which amounts to each person's academic institution.
The replacement code reorganizes the captures into "Firstname Lastname (Academic institution)" without commas.
```

##### After:  
Bryan Ballif (University of Vermont)  
Aaron Ellison (Harvard Forest)  
Sydne Record (Bryn Mawr)  

### 3.
##### Before:  
0001 Georgia Horseshoe.mp3 0002 Billy In The Lowground.mp3 0003 Cherokee Shuffle.mp3 0004 Walking Cane.mp3  


##### Find: `(\d{2,})`
##### Replace: `\n\1`

```explanation
This code searches for a sequence of two or more number characters to get the initial string of numbers (000x) identifying each track. It then replaces the capture with itself, preceded by a line break, effectively separating each track onto its own line.
```

##### After:  
0001 Georgia Horseshoe.mp3  
0002 Billy In The Lowground.mp3  
0003 Cherokee Shuffle.mp3  
0004 Walking Cane.mp3  

### 4.
##### Before:  
0001 Georgia Horseshoe.mp3  
0002 Billy In The Lowground.mp3  
0003 Cherokee Shuffle.mp3  
0004 Walking Cane.mp3  


##### Find: `(\d+)\s(.+)(\.mp3)`
##### Replace: `\2_\1\3`

```explanation
The first capture gets each track's initial string of numbers (000x), and the "\s" accounts for the space. The second capture gets the song title by grouping all the characters up until the third capture, which isolates the ".mp3" at the end of each file.
I then reorganized the captures (plus an underscore) as "song title_000x.mp3" per the instructions.
```

##### After:  
Georgia Horseshoe_0001.mp3  
Billy In The Lowground_0002.mp3  
Cherokee Shuffle_0003.mp3  
Walking Cane_0004.mp3  

### 5.
##### Before:   
Camponotus,pennsylvanicus,10.2,44   
Camponotus,herculeanus,10.5,3  
Myrmica,punctiventris,12.2,4  
Lasius,neoniger,3.3,55  


##### Find: `(\w)\w+,(\w+),.+,(\d+)`
##### Replace: `\1_\2,\3`

```explanation
The first capture gets the first letter of the genus, then the code goes through the rest of the genus name followed by the comma; the second capture gets the species name, and again is followed by a comma. ".+," accounts for the first numeric variable and comma, while the third capture gets the second numeric variable.
Again, the replacement code just reorganizes the captures, separated by an underscore and a comma, into "G_species,#"
```

##### After:  
C_pennsylvanicus,44  
C_herculeanus,3  
M_punctiventris,4  
L_neoniger,55  

### 6.
##### Before:  
Camponotus,pennsylvanicus,10.2,44  
Camponotus,herculeanus,10.5,3  
Myrmica,punctiventris,12.2,4  
Lasius,neoniger,3.3,55  


##### Find: `(\w)\w+,(\w{4})\w+,.+,(\d+)`
##### Replace: `\1_\2,\3`

```explanation
This solution is nearly identical to the previous one (5), with the only difference in the species name. It separates the species name into its first four letters (the second capture), followed by the rest of the word ("\w+"), which is irrelevant to the result and therefore not a part of the capture.
```

##### After:  
C_penn,44  
C_herc,3  
M_punc,4  
L_neon,55  

### 7.
##### Before:  
Camponotus,pennsylvanicus,10.2,44  
Camponotus,herculeanus,10.5,3  
Myrmica,punctiventris,12.2,4  
Lasius,neoniger,3.3,55  

##### Find: `(\w{3})\w+,(\w{3})\w+,(.+),(\d+)`
##### Replace: `\1\2, \4, \3`

```explanation
Again, this solution is similar to the previous few. The first and second captures get the first 3 letters of the genus and species names, respectively. "\w+," accounts for the rest of each word and the comma after each one. The third and fourth captures represent each numeric variable, separated by a comma. 
The replacement code concatenates the first two captures (the first 3 letters of genus and species), followed by a comma, space, and the two numeric variables in reverse order.
```

##### After:  
Campen, 44, 10.2  
Camher, 3, 10.5  
Myrpun, 4, 12.2  
Lasneo, 55, 3.3  




